config/routes.rb
Clibr::Application.routes.draw do
  get "inicio/index"

  resources :paragrafos

  devise_for :usuarios

  devise_scope :usuario do
    match "register"  => "devise/registrations#new"
    get "login"  => "devise/sessions#new"
    get "logout" => "devise/sessions#destroy"
  end

  root :to => "inicio#index"

end

app/models/paragrafo.rb
class Paragrafo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end

end

app/controllers/paragrafos_controller.rb
class ParagrafosController < ApplicationController
  # GET /paragrafos
  # GET /paragrafos.xml
#
  before_filter :authenticate_usuario!

  def index

  #  if @user.curre
    @paragrafos = Paragrafo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @paragrafos }
    end
  end

  # GET /paragrafos/1
  # GET /paragrafos/1.xml
  def show
    @paragrafo = Paragrafo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paragrafo }
    end
  end

  # GET /paragrafos/new
  # GET /paragrafos/new.xml
  def new
    @paragrafo = Paragrafo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paragrafo }
    end
  end

  # GET /paragrafos/1/edit
  def edit
    @paragrafo = Paragrafo.find(params[:id])
  end

  # POST /paragrafos
  # POST /paragrafos.xml
  def create
    @paragrafo = Paragrafo.new(params[:paragrafo])

    respond_to do |format|
      if @paragrafo.save
        format.html { redirect_to(@paragrafo, :notice => 'Paragrafo was successfully created.') }
        format.xml  { render :xml => @paragrafo, :status => :created, :location => @paragrafo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paragrafo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /paragrafos/1
  # PUT /paragrafos/1.xml
  def update
    @paragrafo = Paragrafo.find(params[:id])

    respond_to do |format|
      if @paragrafo.update_attributes(params[:paragrafo])
        format.html { redirect_to(@paragrafo, :notice => 'Paragrafo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paragrafo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /paragrafos/1
  # DELETE /paragrafos/1.xml
  def destroy
    @paragrafo = Paragrafo.find(params[:id])
    @paragrafo.destroy

    respond_to do |format|
      format.html { redirect_to(paragrafos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/paragrafos_helper.rb
module ParagrafosHelper
end

app/views/inicio/gerar_internetes.html.erb
<div id="conteudocaixa" name='conteudocaixa'>
</div>

app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>

TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>
TEM QUE COLOCAR O LAYOUT SHOW DE BOLA AQUI! xD<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<div class="wrapper">
<head>
  <title>Clibr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="logo"></div>

<div id= "container">
<div id="lateralesquerda">
          <div id="internes"></div>
         <div id="troll"></div>
          <div id="barralogo"></div>
</div>
  <div id="qualestilo"></div>
  <div id="conteudo">
    <%= yield %>
   </div>
<div id="lateraldireita">
          <div id="classico"></div>
          <div id="machado"></div>
          <div id="barrabotoes">
            <a href="www.facebook.com/mariojorgevalle"><div id="facebook"></div></a>
            <a href="http://www.twitter.com/clibr"><div id="twitter"></div></a>
            <div id="nos"></div>
            <div id="clibr"></div>
          </div>
</div>

</body>
</div>
</html>

app/views/paragrafos/_form.html.erb
<script language="Javascript">
function Contar(campo){
  document.getElementById("Qtd").innerHTML = campo.value.length;
  if(campo.value.length >= 700){
    alert("Não pode ter mais de 700 caracteres");}
  }
</script>

<%= form_for(@paragrafo) do |f| %>
  <% if @paragrafo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paragrafo.errors.count, "error") %> prohibited this paragrafo from being saved:</h2>

      <ul>
      <% @paragrafo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.select :categoria, options_for_select(["Sucesso nas Internês", "Clássicos da literatura"]) %>
  </div>
  <div class="field">
    <%= f.label :conteudo %> (máximo de 700 caracteres)<br />

   <%= f.text_area :conteudo, :size => '80x10', :onKeyUp => "Contar(this);", :onLoad => "Contar(this);" %><br/>
    <div id="Qtd">0</div>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paragrafos/edit.html.erb
<h1>Editing paragrafo</h1>

<%= render 'form' %>

<%= link_to 'Show', @paragrafo %> |
<%= link_to 'Back', paragrafos_path %>

app/views/paragrafos/index.html.erb
<h1>Listing paragrafos</h1>

<table>
  <tr>
    <th>Categoria</th>
    <th>Conteudo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paragrafos.each do |paragrafo| %>
  <tr>
    <td><%= paragrafo.categoria %></td>
    <td><%= paragrafo.conteudo %></td>
    <td><%= link_to 'Show', paragrafo %></td>
    <td><%= link_to 'Edit', edit_paragrafo_path(paragrafo) %></td>
    <td><%= link_to 'Destroy', paragrafo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paragrafo', new_paragrafo_path %>

app/views/paragrafos/new.html.erb
<h1>New paragrafo</h1>

<%= render 'form' %>

<%= link_to 'Back', paragrafos_path %>

app/views/paragrafos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Categoria:</b>
  <%= @paragrafo.categoria %>
</p>

<p>
  <b>Conteudo:</b>
  <%= @paragrafo.conteudo %>
</p>


<%= link_to 'Edit', edit_paragrafo_path(@paragrafo) %> |
<%= link_to 'Back', paragrafos_path %>